### ISSUE TITLE
OOMDP representation missing Relations?

### ISSUE THREAD

**Issue by banerjs** [david-abel/simple_rl#11]
From Diuk et al, the OOMDP state should also include relations that are calculated as functions of object attributes. However, this seems to be missing in the current implementation of the OOMDP. Are there any plans of adding that to the representation? Am I missing something? Or should I just go ahead and augment the OOMDP state with my own implementation of relations?

**Comment by david-abel** [comment]
Good point!

The OO-MDP state itself is defined as the union over object states, where an object state is an assignment to each of the object's attributes. (See page 2 of the [OO-MDP conference paper](https://www.researchgate.net/profile/Carlos_Diuk/publication/221346111_An_object-oriented_representation_for_efficient_reinforcement_learning/links/0deec516f111b4ad0e000000/An-object-oriented-representation-for-efficient-reinforcement-learning.pdf), paragraph beginning "We depart from...").

So, the relations are an important expressive tool, but are not a part of the state itself -- if you want to include relations in a domain that you're instantiating as an OO-MDP, then you'll need to implement them as boolean function (on object pairs, probably) to accompany the domain and use as you wish.

Does that help?
