### ISSUE TITLE
About drawing plots.

### ISSUE THREAD

**Issue by YuhangSong** [david-abel/simple_rl#27]
Really helpful and neat project! I should definitely express my appreciation to you for releasing such a project.

I am trying to produce the plot figure with shallow background:
![image](https://user-images.githubusercontent.com/28839288/44845455-2a48b700-ac80-11e8-97f3-17badad5aea7.png)
However, my reward curve looks like this 
![image](https://user-images.githubusercontent.com/28839288/44845501-49dfdf80-ac80-11e8-9aff-7d300d70198f.png)
Thus the computed conf_interv is zero.

Is there a parameter I can set to make the shallow background appear in my case?

**Comment by david-abel** [comment]
In the second plot, it looks like you're producing an average reward plot -- I would guess that when you call the run_agents_on_mdp function, the "cumulative_plot" parameter is set to false. It also looks like your experiment only has one instance. So, try doing the following:

- When you call run_agents_on_mdp, pass in "cumulative_plot=True" as an argument.
- Increase the number of instances. So, when you call run_agents_on_mdp, set "instances=X", for some X > 1.

Hope this helps! If it doesn't fix things, could you please show some of the code you're running to produce the above plots?

**Comment by david-abel** [comment]
Any further issues? Did my suggestion above fix things? If so I'll close this issue.

**Comment by YuhangSong** [comment]
Yes, your suggestions have been help a lot! Sorry that I replied your comments from mobile phone and it seems that the message does not reach here.

You can close the issue, my problem is well solved by your comments. Thank you so much for that!

**Comment by david-abel** [comment]
Great, glad that helped!
