### ISSUE TITLE
Visualizing GridWorld example

### ISSUE THREAD

**Issue by apollokit** [david-abel/simple_rl#36]
Hi,
Great looking project. 

I'd like to get visualization (in pygame) of an agent moving through the gridworld example working, if possible. It seems like there's infrastructure in place for it: the visualize_() methods under simple_rl/tasks/grid_world/GridWorldMDPClass.py. Looks like it might be deprecated though? And it's not clear to me where the pygame viz is supposed to happen within the call stack.

For context, I'm running the example on this page https://david-abel.github.io/blog/posts/simple_rl.html, successfully. 

Thanks!

**Comment by david-abel** [comment]
Hi, thanks for the interest!

Regarding visualization, those methods should be working -- can you try running [viz_example.py](https://github.com/david-abel/simple_rl/blob/master/examples/viz_example.py)? If you have pygame installed, you should see a Q-learning agent learning in a grid world. There are a few other options for visualizing as well, which you can explore by changing the "viz" variable in viz_example.py itself. Let me know if you have any issues!

I will say that the visuals are not as integrated as many other parts of the library. If you have thoughts on how to improve it I'd love to see it strengthened.

The basic structure for visuals, so far,  has been to have each task implement a "visualize_X" method, as visuals for grid worlds will differ from other kinds of MDPs. Let me know if you have any other thoughts/questions!

Best,
-Dave

**Comment by apollokit** [comment]
Thanks for the quick response!

I'm able to run viz_example.py, but unfortunately having trouble with pygame still...the "pygame window" pop up is just blank! Running python 2.7.10 with pygame 1.9.4 under MacOS 10.14.2. Also tried installing pygame under python 3.5.4 and the "pip install pygame" straight up breaks at compilation. :/

What are you able to run it under?

**Comment by david-abel** [comment]
Hm, that is puzzling! I run either python 2.7.14 or 3.6.5 with pygame 1.9.4 on MacOS 10.13.6.

Perhaps there's something in MacOS 10.14? That's strange. I'll poke around and let you know if I find any fixes.

**Comment by david-abel** [comment]
Following up -- I think I've fixed the issue. Try updating to simple_rl version 0.811 (I just updated pypi as well so you should be able to just do a pip install --update). Let me know if that works

**Comment by david-abel** [comment]
I'm going to mark this as closed as it seems to be working now, but let me know if that's not the case.
