### ISSUE TITLE
Forcing the use of the TkAgg Matplot lib backend prevents usage in notebooks

### ISSUE THREAD

**Issue by philwinder** [david-abel/simple_rl#40]
Hi there. In a few places you force the use of TkAgg. In the past this was necessary to work on certain systems, but I believe this is no longer the case with newer versions of Matplotlib.

However, forcing TkAgg breaks the code on, for example, Google Colab.

I see it was introduced in this commit: https://github.com/david-abel/simple_rl/commit/e089dd920cf0dec65e970a83fd97ae123498c35a

I think the easiest solution is to revert that commit and test again on the original system that was having issues (probably OSX).

Here is the most simple reproduction: https://colab.research.google.com/gist/philwinder/148a4a54d0a7fdc1a10677f30da2da57/untitled6.ipynb

This:
```
!pip install simple_rl
from simple_rl.tasks import GridWorldMDP
```

Thanks!

**Comment by david-abel** [comment]
Yes, indeed the TkAgg backend was being used to fix some issues on OSX. I will test taking TkAgg out, thanks!

**Comment by david-abel** [comment]
Should be fixed now, let me know if issues persist and I will reopen this issue.

**Comment by philwinder** [comment]
Hi @david-abel, thanks for this.
There is another tkagg reference here: https://github.com/david-abel/simple_rl/blob/master/simple_rl/tasks/gather/GatherStateClass.py

This is imported through a chain of files to end up in the same `simple_rl.tasks` package, so the test above still fails.

**Comment by david-abel** [comment]
Hi Phil,

Should be fixed -- I added a condition to check for Mac OS, which is what requires TkAgg. Let me know if it persists.

Cheers,
-Dave

**Comment by jacksondc** [comment]
I'm not seeing this change on pip or in the tarball linked in the README—is it possible a new version hasn't been released this got fixed?
