### ISSUE TITLE
Invalid policy visualization due to use of e-greedy action

### ISSUE THREAD

**Issue by philwinder** [david-abel/simple_rl#42]
For the [visualize_policy function](https://github.com/david-abel/simple_rl/blob/master/simple_rl/utils/mdp_visualizer.py#L94) you have to pass a policy for it to plot. But most of the time we just pass the policy used for training (see the [viz_example](https://github.com/david-abel/simple_rl/blob/10a3c0f5198d4230bc9e6a895689c5252fd7fcc2/examples/viz_example.py#L40) for an example).

This means that the policy will be affected by the exploration function (e.g. e-greedy) and therefore 1 in ten times you get an incorrect policy.

I'm not sure if it is a good idea to add a `greedy` option flag, to prevent the use of any e-greedy action. But obviously that would have to be changed for all agents.

**Comment by david-abel** [comment]
Hm, I think it makes sense to keep the function as is (accept a policy as input), and just take care when passing a policy. Perhaps Q based agents would like a method that gets the pure greedy policy and ignores exploration (softmax/e-greedy)?

**Comment by david-abel** [comment]
I'm going to close this, and take the resolution to be letting the user dictate which policy they pass in.
