### ISSUE TITLE
'can't pickle dict_values objects' when running "belief_mdp_example.py" with Python 3

### ISSUE THREAD

**Issue by zkytony** [david-abel/simple_rl#43]
I get the following error traceback when running `python belief_mdp_example.py` on the master branch. I am using Python 3.5.2.

```
Traceback (most recent call last):
  File "belief_mdp_example.py", line 14, in <module>
    main()
  File "belief_mdp_example.py", line 8, in main
    belief_mdp = BeliefMDP(pomdp)
  File "/home/kaiyuzh/repo/simple_rl/simple_rl/pomdp/BeliefMDPClass.py", line 20, in __init__
    BeliefState(pomdp.init_belief), pomdp.gamma, pomdp.step_cost)
  File "/home/kaiyuzh/repo/simple_rl/simple_rl/mdp/MDPClass.py", line 14, in __init__
    self.init_state = copy.deepcopy(init_state)
  File "/home/kaiyuzh/pyenv/py3/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/kaiyuzh/pyenv/py3/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/kaiyuzh/pyenv/py3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/kaiyuzh/pyenv/py3/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/kaiyuzh/pyenv/py3/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle dict_values objects
```

It looks like an issue with compatibility with python 3.

**Comment by zkytony** [comment]
This can be fixed if we change
```
State.__init__(self, data=belief_distribution.values())
```
to 
```
State.__init__(self, data=list(belief_distribution.values()))
```
`BeliefStateClass.py.__init__`

Is this a good fix?

**Comment by david-abel** [comment]
Yes, that looks like a good fix -- if you submit a pull request with the change I'm happy to approve it (otherwise I should be able to get to it sometime soon)

**Comment by zkytony** [comment]
Do we want to assume "belief_distribution.values()" to always return something that can be turned into a list? I'm working on an implementation of belief distribution for my problem, which has a very large state space, so I think it would be inefficient to list all of them out. I'm thinking of implementing the `__getitem__`, `__setitem__`, `__len__`, etc. functions for this belief distribution, so that `State` can still use this belief distribution as data. In general, should I pursue something like this when the state space is very large?

Also, currently in `POMDP` class, the constructor needs `observations` which is never used in other parts of the library (only `observation_func` is used), and it is also quite infeasible to list all the observations when the space is very large. I suggest removing `observations` from the constructor of `POMDP`.

**Comment by zkytony** [comment]
I wonder, how large is the largest POMDP that people have tried with simple_rl?

**Comment by david-abel** [comment]
Up to you! I haven't used the BeliefMDP/POMDP really -- that has been developed/used by other folks so I don't have the best handle on the size of POMDPs of interest.

MDPs tend to be small (less than 10k states, typically). If you get around to implementing the __getitem__ etc let me know. For now I will add the list cast as a quick fix.

**Comment by zkytony** [comment]
Thanks for reply! I have made some progress implementing POMCP and OOPOMDP/OOPOMCP (now tested on a 2D maze). I also made some changes to existing POMDP code (the structure of existing code helped me a lot!). I will probably make a PR soon once I finish this round of work.

**Comment by zkytony** [comment]
I have another question regarding convention in simple_rl. It seems like right now every class gets its own "ClassNameClass.py" file. I find it a bit inconvenient to create so many files, so I put, for example, the classes related to OOPOMDP in a single file for OOPOMDP, etc. Is this acceptable?

**Comment by david-abel** [comment]
Sounds good Re: the PR!

Regarding ....Class.py, I am not attached to that convention, it was just helpful for me in the early days of writing the library. I think having several related classes in one file is totally reasonable.

**Comment by david-abel** [comment]
Going to close this one for now: I added the cast to the belief state distribution. If any problems persist we can reopen the issue.
