### ISSUE TITLE
Issues Running Example, open is not recognized as an internal or external command

### ISSUE THREAD

**Issue by seand88** [david-abel/simple_rl#47]
`
import simple_rl

from simple_rl.agents import QLearningAgent

from simple_rl.tasks import GridWorldMDP

from simple_rl.run_experiments import run_agents_on_mdp
mdp = GridWorldMDP(10, 10, goal_locs=[(10,10)])
ql_agent = QLearningAgent(mdp.get_actions())
run_agents_on_mdp([ql_agent], mdp, steps=100)
`

Ran this code on windows.
Received 'open' is not recognized as an internal or external command,
operable program or batch file.

Python version 3.7

**Comment by david-abel** [comment]
Good catch! The plotting was not equipped to handle windows platforms gracefully. Should be fixed with the latest [commit](https://github.com/david-abel/simple_rl/commit/b95b2402b17af333ec66f54c720124da898627b5). Let me know if the issue persists.

**Comment by seand88** [comment]
is there a way to open the plot on windows?
I would like to be able to see it?

**Comment by seand88** [comment]
also i installed it with pip, but it doesnt pick up any version change. not sure how i would use it from the download, semi new to python.

**Comment by seand88** [comment]
i did try to open the results.pdf but it doesnt look right, looks garbled

**Comment by david-abel** [comment]
Re opening the plot in windows: I don't have a windows machine so I can't test it, but it sounds like the "start" command should work. If you test that and it does work, let me know and I can add it to the library. To test, open up a shell and change to the directory containing results.pdf and try executing "start results.pdf". If the plot opens, that would be good to know.

Regarding pip installation: I will need to propagate changes made to the repository over to the python package index, which will take a bit of time. I can let you know when that's done and you can test. If you want to avoid that open error in the meantime, you should be able to clone the repository and run things from within the cloned repo.

Re: garbled results. What does the plot look like? Could you email me a picture of the plot, and perhaps let me know which script you're running? My email is david_abel@brown.edu. Thanks!

**Comment by david-abel** [comment]
Seems like this was resolved by the pull request -- thanks!
