### ISSUE TITLE
brtdp_example.py

### ISSUE THREAD

**Issue by oridong** [david-abel/simple_rl#50]
def _qvalue(self, state, action, values):
        return self.mdp.reward_func(state, action) + sum([self.trans_dict[state][action][next_state] * values[next_state]  for next_state in self.states])
发生异常: TypeError
_reward_func() missing 1 required positional argument: 'next_state'

**Comment by david-abel** [comment]
Should be fixed now as of commit [b26d2fb](https://github.com/david-abel/simple_rl/commit/b26d2fb6c94e30f610741ad2c1567d2f752028ea). Let me know if the issue persists!

**Comment by oridong** [comment]
> I think it in dead cycle .
brtdp_example.py  > def run_sample_trial(self, verbose=True):
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
s: (1,1)        Action: down    Gap: 99.0754104965909   MaxDiff: 9.908648275251627
....
