### ISSUE TITLE
Are policy gradient-based agents implemented?

### ISSUE THREAD

**Issue by RylanSchaeffer** [david-abel/simple_rl#59]
I'm looking at the code for your `PolicyGradientAgent` and your `ReinforceAgent` and neither seems to have an act or update function implemented. Am I misunderstanding how your code functions, or are neither implemented?

**Comment by david-abel** [comment]
Hi there! Thanks for your interest -- indeed, those agents are both not implemented at the moment. I can add a note indicating this more precisely, good catch.

**Comment by RylanSchaeffer** [comment]
Can I submit a feature request to have them added? Or should I implement them myself?

**Comment by RylanSchaeffer** [comment]
@david-abel sorry to bother you again, but could I please nudge you for an answer?
