### ISSUE TITLE
Is Q Learning Softmax agent correctly implemented?

### ISSUE THREAD

**Issue by RylanSchaeffer** [david-abel/simple_rl#60]
I tried the Q-Learning agent with a softmax policy and found that it's barely better than a random agent:

![image](https://user-images.githubusercontent.com/8942987/135960124-3e03afe4-ac7f-4d50-a55c-0d885a7766e6.png)

That seems wrong. Is this agent implemented correctly?

**Comment by RylanSchaeffer** [comment]
I'm 99% sure that the PG agent doesn't do anything, so it incurs no penalties, so it looks best but that's wrong.

**Comment by david-abel** [comment]
Hi there! Thanks for checking in about this -- to my knowledge, softmax Q-learning does work, but is sensitive to choice of temperature ("beta" in the get_action_distr method in QLearningAgent) and Q-initilialization. It might be worth playing with the choice of temperature parameter on a few different tasks to see whether it works. I'm "OOO" at the moment but can play with this as well when I return
