### ISSUE TITLE
RMAX is slow and not implemented correctly 

### ISSUE THREAD

**Issue by zhouzypaul** [david-abel/simple_rl#62]
Hi Dave, I was going through the RMAX code and noticed that thing may not be implemented correctly. 

Specifically: 
- the initial Q values are initialized to `R_max`, but should really be `R_max * 1/(1-gamma)`. 
- for each time step, the agent is doing an update step first, and then choosing the action. It should choose the action before doing the update
- for each update step, the agent only updates the Q values of (s, a) pairs that it has seen before. It should update Q values of all the (s, a) pairs (that have been seen enough times). 

Also, the code ran really slow for me even on small 2D grid worlds (5x5, for example), mostly because of the triple-nested for loop used to do the Q value update.

I have submitted a PR that fixes all the issues mentioned above, and uses numpy to avoid the for loop to speed up the update.

**Comment by david-abel** [comment]
Thanks! I just merged your pull request -- I'll close the issue for now but let me know if you would like to reopen.
