### ISSUE TITLE
Python3: import errors

### ISSUE THREAD

**Issue by yrevar** [david-abel/simple_rl#7]
Hi there!

I used setup.py to install current version of the library as apparently APIs have changed after the latest release. Trying to run the example from README, I get following error:
```
from simple_rl.run_experiments import run_agents_on_mdp

----> 4 from simple_rl.run_experiments import run_agents_on_mdp
      5 from simple_rl.tasks import GridWorldMDP
      6 from simple_rl.agents import QLearnerAgent
.../simple_rl/__init__.py in <module>()
     28 License: MIT
     29 '''
---> 30 import agents, experiments, mdp, planning, tasks, utils
     31 import run_experiments

ModuleNotFoundError: No module named 'agents'
```
As a workaround fix, I extended sys.path with directory containing "simple_rl". But then I got more errors like
`ModuleNotFoundError: No module named 'AgentClass'`

I'm no Python3 expert, is there any quick fix to solve these issues? Which release do you recommend for conducting more experiments? I'm planning to use MDP worlds, and several RL algorithms.

**Comment by david-abel** [comment]
Hi Yagnesh,

The python 3 support is still relatively new, so thanks for your patience as I iron out the kinks.

Unfortunately it looks like the same command works in Python 2 (while I was able to reproduce the issue in Python 3), so it's definitely something unique to imports in Python 3. I'll take a look and let you know what I find.

**Comment by yrevar** [comment]
Okay, thanks for the tips. I also didn't see any such issue with Python 2.

I think I've found what's causing it, most likely the issue described [here](https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) 

Seems explicit relative imports are needed for Python 3. So imports that assume current directory would need to change from "import <module name>" to "import .<module name>".

**Comment by david-abel** [comment]
Yes, that's exactly the issue, good catch! I just pushed a change to master that updates all relative imports to the absolute path (so "import agents" --> "import simple_rl.agents").

I just ran a few tests for both Python 2 and Python 3 and everything passed on my end, so fingers crossed the problem is resolved. Let me know if any other issues arise!

**Comment by yrevar** [comment]
Cool, thanks! 

For queue vs. Queue, if you are okay with "future" module:

```
# Python 2 and 3 (after ``pip install future``):
from queue import Queue, heapq, deque
```

I took it from the several tips presented here: http://python-future.org/compatible_idioms.html

**Comment by yrevar** [comment]
Thanks for your support David! Closing this one.
